version: "3.1"
services:
    api_nginx:
      image: nginx:alpine
      container_name: api_nginx
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - .:/application
        - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      networks:
        - api

    api_php:
      build: ./.docker
      container_name: api_php
      restart: unless-stopped
      tty: true
      working_dir: /api
      volumes:
        - ./api:/api
      networks:
        - api

    node:
      image: node:12
      ports:
        - '8081:8080'
      volumes: 
        - ./app:/srv/app
      working_dir: /srv/app
      command: 'npm run serve'
      networks:
        - api

networks:
  api:
    driver: bridge
